networks:
  kafka_network:
    driver: bridge

services:
  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    # network_mode: "host"
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: "6hvjsELATxiPPpB0lrg5KA"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-1:9092,CONTROLLER://kafka-broker-1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      # KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093,2@localhost:19093,3@localhost:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - "9092:9092"
    volumes:
      - kafka_broker1_data:/var/lib/kafka/data

  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-2
    # network_mode: "host"
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER_ID: 2
      CLUSTER_ID: "6hvjsELATxiPPpB0lrg5KA"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-2:9094,CONTROLLER://kafka-broker-2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      # KAFKA_LISTENERS: PLAINTEXT://localhost:9094,CONTROLLER://localhost:19093
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:19093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093,2@localhost:19093,3@localhost:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - "9094:9094"
    volumes:
      - kafka_broker2_data:/var/lib/kafka/data

  kafka-broker-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-3
    # network_mode: "host"
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER_ID: 3
      CLUSTER_ID: "6hvjsELATxiPPpB0lrg5KA"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-3:9095,CONTROLLER://kafka-broker-3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9095
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      # KAFKA_LISTENERS: PLAINTEXT://localhost:9095,CONTROLLER://localhost:29093
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9095,CONTROLLER://0.0.0.0:29093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093,2@localhost:19093,3@localhost:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - "9095:9095"
    volumes:
      - kafka_broker3_data:/var/lib/kafka/data
  

  # (2) Kafka Initialization Service
  init-kafka:
    image: confluentinc/cp-kafka:latest
    # network_mode: "host"
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    networks:
      - kafka_network
    volumes:
      - ./init-kafka.sh:/usr/bin/init-kafka.sh
    entrypoint: /bin/sh -c "/usr/bin/init-kafka.sh"

  # (3) MinIO Service
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: server /data --console-address ":9001"


volumes:
  minio-data:
  minio-config:
  kafka_broker1_data:
  kafka_broker2_data:
  kafka_broker3_data: