[general]
kafka_topic = 'event-messages' 
root_path = './consumer_output'
consumer_batch_size = 10
flush_interval = 8 # Seconds
max_output_file_size = 4194304 # 4Mb in bytes

[producer]
bootstrap_servers = "localhost:9092"
retries = 2147483647
max_in_flight_requests_per_connection = 1 # TODO: To enable retries without reordering
acks = 'all'
batch_size = 16384
enable_idempotence = true # TODO: Best practices for analytics systems, optimize for performance
delivery_timeout_ms = 120000
linger_ms = 5
request_timeout_ms = 30000

# TODO: Figure out which configs should be here
[consumer]
bootstrap_servers = "host1:9092,host2:9092"
group.id = 'test_events_consumer_group'
partition.assignment.strategy = 'range'
auto.offset.reset = 'smallest'