[general]
kafka_topic = 'event-messages' # TODO: Can it be imported from somewhere since it is used here and in producer as well?
min_commit_count = 10 # TODO: Move to config, how much to put? 
root_path = 'consumed-events'
max_output_file_size = 4194304 # 4Mb in bytes

[producer]
bootstrap_servers = "localhost:9092"
retries = 2147483647
max_in_flight_requests_per_connection = 1 # TODO: To enable retries without reordering
acks = 'all'
batch_size = 16384
enable_idempotence = true # TODO: Best practices for analytics systems, optimize for performance
delivery_timeout_ms = 120000
linger_ms = 5
request_timeout_ms = 30000

# TODO: Figure out which configs should be here
[consumer]
bootstrap_servers = "host1:9092,host2:9092"
group.id = 'foo'
auto.offset.reset = 'smallest'