# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/context.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x65vents/context.proto\x12\x06\x65vents"\xd6\x01\n\x0c\x45ventContext\x12\x14\n\x07sent_at\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x18\n\x0breceived_at\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x19\n\x0cprocessed_at\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x17\n\nmessage_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\nuser_agent\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\n\n\x08_sent_atB\x0e\n\x0c_received_atB\x0f\n\r_processed_atB\r\n\x0b_message_idB\r\n\x0b_user_agentb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "events.context_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_EVENTCONTEXT"]._serialized_start = 33
    _globals["_EVENTCONTEXT"]._serialized_end = 247
# @@protoc_insertion_point(module_scope)
