# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/test_events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65vents/test_events.proto\x12\x06\x65vents\"\xd6\x01\n\x0c\x45ventContext\x12\x14\n\x07sent_at\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x18\n\x0breceived_at\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x19\n\x0cprocessed_at\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x17\n\nmessage_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\nuser_agent\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\n\n\x08_sent_atB\x0e\n\x0c_received_atB\x0f\n\r_processed_atB\r\n\x0b_message_idB\r\n\x0b_user_agent\"\xed\x01\n\tTestEvent\x12*\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x14.events.EventContextH\x00\x88\x01\x01\x12\x17\n\nevent_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07user_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\naccount_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12(\n\tuser_role\x18\x05 \x01(\x0e\x32\x10.events.UserRoleH\x04\x88\x01\x01\x42\n\n\x08_contextB\r\n\x0b_event_nameB\n\n\x08_user_idB\r\n\x0b_account_idB\x0c\n\n_user_role\"\x94\x02\n\x13YetAnotherTestEvent\x12*\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x14.events.EventContextH\x00\x88\x01\x01\x12\x17\n\nevent_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12*\n\ninput_type\x18\x03 \x01(\x0e\x32\x11.events.InputTypeH\x02\x88\x01\x01\x12\x16\n\tobject_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12,\n\x0bobject_type\x18\x05 \x01(\x0e\x32\x12.events.ObjectTypeH\x04\x88\x01\x01\x42\n\n\x08_contextB\r\n\x0b_event_nameB\r\n\x0b_input_typeB\x0c\n\n_object_idB\x0e\n\x0c_object_type*-\n\x08UserRole\x12\t\n\x05OWNER\x10\x00\x12\n\n\x06\x45\x44ITOR\x10\x01\x12\n\n\x06VIEWER\x10\x02*<\n\nObjectType\x12\x08\n\x04\x43\x41RD\x10\x00\x12\x0f\n\x0bSTICKY_NOTE\x10\x01\x12\x08\n\x04TEXT\x10\x02\x12\t\n\x05IMAGE\x10\x03*?\n\tInputType\x12\x11\n\rSIMPLE_SELECT\x10\x00\x12\x08\n\x04MOVE\x10\x01\x12\n\n\x06ROTATE\x10\x02\x12\t\n\x05SCALE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.test_events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERROLE']._serialized_start=772
  _globals['_USERROLE']._serialized_end=817
  _globals['_OBJECTTYPE']._serialized_start=819
  _globals['_OBJECTTYPE']._serialized_end=879
  _globals['_INPUTTYPE']._serialized_start=881
  _globals['_INPUTTYPE']._serialized_end=944
  _globals['_EVENTCONTEXT']._serialized_start=37
  _globals['_EVENTCONTEXT']._serialized_end=251
  _globals['_TESTEVENT']._serialized_start=254
  _globals['_TESTEVENT']._serialized_end=491
  _globals['_YETANOTHERTESTEVENT']._serialized_start=494
  _globals['_YETANOTHERTESTEVENT']._serialized_end=770
# @@protoc_insertion_point(module_scope)
