[producer]
bootstrap_servers = ["localhost:9092"]
retries = 2147483647
max_in_flight_requests_per_connection = 1 # To enable retries without reordering
acks = 'all'
batch_size = 16384
enable_idempotence = true # TODO: Best practices for analytics systems, optimize for performance
delivery_timeout_ms = 120000
linger_ms = 5
request_timeout_ms = 30000
