name: CI event-collector

on:
  push:
    branches: ["**"]
    tags: ["**"]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/on_push.yml'

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install --upgrade pip && pip install -U poetry==1.6.1 poetry-plugin-export==1.5.0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - name: Setup and run tests
        working-directory: .
        run: |
          poetry install
          make battery
